version: 2
endpoint: http://localhost:8082
metadata_directory: metadata
admin_secret: myadminsecretkey
enable_telemetry: false
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
